Crux SaaS node express server init
cruxprotocol/js-sdk pull request #200
Opened 2020-05-20 12:09 UTC by SanchayPahalwani

2020-05-20 12:23 UTC, quixote911 requested changes

2020-05-20 12:23 UTC, quixote911 commented on package.json
> +    "build-and-start-saas-server": "./node_modules/.bin/parcel build ./src/application/clients/crux-saas-server/node-app.ts -d dist --out-file crux-saas-server.js --no-minify --no-cache --detailed-re
Remove parcel involvement, use ts-node

2020-05-21 06:03 UTC, SanchayPahalwani commented on package.json
> +    "build-and-start-saas-server": "./node_modules/.bin/parcel build ./src/application/clients/crux-saas-server/node-app.ts -d dist --out-file crux-saas-server.js --no-minify --no-cache --detailed-re
Updated

2020-05-28 23:35 UTC, quixote911 commented
Lots of new code has been merged into feature/p2pmessaging, now cruxWalletClient.sendPaymentRequest and receivePaymentRequest is working perfectly.

Lets test `cruxWalletClient.sendPaymentRequest` with this server and add it to the whitelist.

2020-06-04 07:51 UTC, quixote911 commented
Looks good!

2020-06-04 07:53 UTC, quixote911 approved these changes

2020-06-04 07:54 UTC, merged